### ISSUE TITLE
Tank tube backstuffs injection tube when on the same network

### ISSUE THREAD

**Issue by target-san** [Schmoller/Tubes#20]
Per my observations, tank tube would attempt to push more and more liquid payloads into network, regardless of there's a destination for them or not. When there's any overflow destination, it becomes jammed. Really annoying.

Real example
I had two dynamos supplied with tubes with water and charcoal. Water was produced by aqueous accumulator and pushed into network with tank tube. Then it just jammed injection tube with water and prevented dynamos from working further.

**Comment by Schmoller** [comment]
I have seen this too however it is not a bug since it is designed to find the nearest place it can go. Currently the only solution is to use filter tubes since they are always obeyed. In the future I will be adding a whole range of smart tubes that will act in ways that reduce the likely hood of the system jamming, for example, not pushing into the network something that doesnt fit, only allowing certain items to overflow in certain places, etc., however I currently do not have much time to work on Tubes so these changes are a while off.
So yes, it is annoying but you can make it work by adding a filter tube in front of the fuel input that prevents water from entering.

**Comment by target-san** [comment]
I'd rather make 'less but more', i.e. less tubes with more functions. Otherwise it would become another BC pipes. I'd also add some of 'pre-lookup' and compression to basic tubes themselves. Though it's your mod, not mine :)
